### ISSUE TITLE
Create a Employee Training join table

### ISSUE THREAD

**Issue by kayrahbear** [illegal-llamas/Banagzon-LLC#52]
#### Context
***
   * Create an employee training table to join the many to many relationship between the employee table and the training program table. This table will not be exposed to the API and therefor will not require a view.

   
#### Associated product ticket
***
   * N/A

#### Process
***

  * Within bangazon/api/models.py, create a new model titled EmployeeTraining. Refer to the Bangazon ERD.png file (located in this repository) for details on what columns to include.
- These changes may encounter merge conflicts because multiple team members are working on the same files.

   
   
#### Expected Result
***
   * Join the employee and training program tables

**Comment by jnelsontn** [comment]
👍
